package render

import (
	"bytes"
	"fmt"
	"path/filepath"

	"github.com/shuuuumai96/md-merge/internal/merge"
)

func Markdown(cfg merge.Config, files []merge.FileRecord, contents map[string]string) ([]byte, []merge.Warning, error) {
	var warnings []merge.Warning
	var out bytes.Buffer

	fmt.Fprintln(&out, "# Merged Markdown")
	fmt.Fprintln(&out)
	fmt.Fprintf(&out, "Source directory: `%s`\n", sourceLabel(cfg))
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "Generated by: `md-merge`")
	fmt.Fprintln(&out)

	if cfg.WithTOC {
		writeTOC(&out, files, contents)
	}

	for _, file := range files {
		content, ok := contents[file.DisplayPath]
		if !ok {
			continue
		}
		fmt.Fprintln(&out, "---")
		fmt.Fprintln(&out)
		fmt.Fprintf(&out, "<!-- BEGIN FILE: %s -->\n", file.DisplayPath)
		fmt.Fprintln(&out)
		fmt.Fprintf(&out, "## File: `%s`\n", file.DisplayPath)
		fmt.Fprintln(&out)
		out.WriteString(content)
		if content == "" || content[len(content)-1] != '\n' {
			out.WriteByte('\n')
		}
		fmt.Fprintln(&out)
		fmt.Fprintf(&out, "<!-- END FILE: %s -->\n", file.DisplayPath)
		fmt.Fprintln(&out)
	}

	return out.Bytes(), warnings, nil
}

func writeTOC(out *bytes.Buffer, files []merge.FileRecord, contents map[string]string) {
	fmt.Fprintln(out, "## Files")
	fmt.Fprintln(out)
	for _, file := range files {
		if _, ok := contents[file.DisplayPath]; ok {
			fmt.Fprintf(out, "- `%s`\n", file.DisplayPath)
		}
	}
	fmt.Fprintln(out)
}

func sourceLabel(cfg merge.Config) string {
	if cfg.RootDir == "" {
		return "."
	}
	return filepath.ToSlash(filepath.Clean(cfg.RootDir))
}
